version: '3.8'
services:
  casbin: &casbin
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
  depi:
    <<: *casbin
    entrypoint: composer install
  depu:
    <<: *casbin
    entrypoint: composer update
  test:
    <<: *casbin
    entrypoint: php vendor/bin/phpunit
  stan:
    <<: *casbin
    entrypoint: php vendor/bin/phpstan
